/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());

      Calculate c = new Calculate();
      int in1,in2;
      in1=2;

      String sumave = "Sum of " + 2 + " and " + 3 + " is " + c.sum(2, 3)
          + ". Average is " + c.ave(2, 3) + '.';

      System.out.println(sumave);

      int out1=0;
      for (int i = 1; i <= 10; i++) {
        out1=c.sum()
      }

    }
}
