/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());

      Calculate c = new Calculate();
      int in1,in2;
      in1=2;
      in2=3;

      String sumave = "Sum of " + in1 + " and " + in2 + " is " + c.sum(in1, in2)
          + ". Average is " + c.ave(in1, in2) + '.';

      System.out.println(sumave);

      int out1=0;
      for (int i = 1; i <= 10; i++) {
        out1=c.sum()
      }

    }
}
